//Напишите dockerfile, который создает образ с python приложением, которое выводит на экран “Hello, world!” при запуске контейнера. Запустите контейнер из этого образа и проверьте его работу.
FROM python:3.9-slim

WORKDIR /app

COPY app.py .

RUN pip install flask

CMD [ "python", "app.py" ]
