//Напишите ansible playbook, который устанавливает nginx на две виртуальные машины и настраивает их как прокси-сервера для третьей виртуальной машины, на которой запущено приложение на python.
---
- name: Nginx
  hosts: all
  become: yes

  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: configure nginx
      template:
        src: nginx_proxy.conf.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
